backend:
  name: github
  repo: ASK-STEM-official/stem-docx
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: blog
    label: "Blog"
    folder: blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - { name: title, label: "Title", widget: "string" }
      - { name: body, label: "Body", widget: "markdown" }
      - { name: slug, label: "Slug", widget: "string" }
      - name: tags
        label: "Tags"
        widget: list
      - name: authors
        label: "Authors"
        widget: list
        fields:
          - { name: name, label: "Name", widget: "string" }
          - { name: title, label: "Title", widget: "string" }
          - { name: url, label: "URL", widget: "string" }
          - { name: imageUrl, label: "ImageURL", widget: "string" }
